"""Generate ``docs/telemetry/dashboard.md`` from ``events.jsonl`` (Phase 5).

Usage::

    uv run scripts/telemetry_dashboard.py
    uv run scripts/telemetry_dashboard.py --events path/to/events.jsonl --out path/to/dashboard.md
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_EVENTS = _REPO_ROOT / "docs" / "telemetry" / "events.jsonl"
DEFAULT_OUT = _REPO_ROOT / "docs" / "telemetry" / "dashboard.md"


def load_events(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    events: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped:
            events.append(json.loads(stripped))
    return events


def average_confidence(events: list[dict]) -> float | None:
    values = [
        int(e["reviewer_confidence"]) for e in events if e.get("reviewer_confidence") is not None
    ]
    if not values:
        return None
    return sum(values) / len(values)


def format_table_row(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


def render_dashboard(events: list[dict]) -> str:
    generated = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    route_counts = Counter(e.get("route_decision") for e in events)
    risk_counts = Counter(e.get("risk_tier") for e in events if e.get("risk_tier"))
    avg_conf = average_confidence(events)

    lines = [
        "# Telemetry dashboard",
        "",
        f"_Generated by `scripts/telemetry_dashboard.py` at {generated}._",
        "",
        "## Summary",
        "",
        f"- **Events recorded:** {len(events)}",
        f"- **Average reviewer confidence:** {avg_conf:.1f}"
        if avg_conf is not None
        else "- **Average reviewer confidence:** n/a",
        "",
        "## Route distribution",
        "",
        format_table_row(["Route", "Count"]),
        format_table_row(["---", "---"]),
    ]
    for route, count in sorted(route_counts.items(), key=lambda x: (x[0] or "", x[1])):
        lines.append(format_table_row([str(route), str(count)]))
    if not route_counts:
        lines.append(format_table_row(["(none)", "0"]))

    lines.extend(
        [
            "",
            "## Risk tier distribution",
            "",
            format_table_row(["Risk tier", "Count"]),
            format_table_row(["---", "---"]),
        ]
    )
    for tier, count in sorted(risk_counts.items(), key=lambda x: (x[0] or "", x[1])):
        lines.append(format_table_row([str(tier), str(count)]))
    if not risk_counts:
        lines.append(format_table_row(["(none)", "0"]))

    lines.extend(["", "## Last 20 PRs", ""])
    if not events:
        lines.append("_No events yet. Merge a PR with telemetry recording enabled._")
    else:
        lines.extend(
            [
                format_table_row(
                    [
                        "PR",
                        "Route",
                        "Risk",
                        "Conf.",
                        "Files",
                        "Diff",
                        "Merge",
                    ]
                ),
                format_table_row(["---"] * 7),
            ]
        )
        tail = events[-20:]
        for e in reversed(tail):
            pr = str(e.get("pr_number") or "—")
            lines.append(
                format_table_row(
                    [
                        pr,
                        str(e.get("route_decision") or "—"),
                        str(e.get("risk_tier") or "—"),
                        str(
                            e.get("reviewer_confidence")
                            if e.get("reviewer_confidence") is not None
                            else "—"
                        ),
                        str(e.get("changed_files_count") or "—"),
                        str(e.get("diff_lines") or "—"),
                        str(e.get("merge_outcome") or "—"),
                    ]
                )
            )

    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Render telemetry dashboard markdown.")
    p.add_argument("--events", type=Path, default=DEFAULT_EVENTS)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = p.parse_args(argv)

    events = load_events(args.events)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_dashboard(events), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
